
DROP TABLE IF EXISTS DW_REG.DIM_PERIODO_BKP;

CREATE TABLE DW_REG.DIM_PERIODO_BKP
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC
AS
SELECT
	(YEAR(DT_NASCIMENTO)*10000) + (MONTH(DT_NASCIMENTO)*100) + DAY(DT_NASCIMENTO) AS CD_PERIODO,
	DT_NASCIMENTO AS DT_PERIODO,
	YEAR(DT_NASCIMENTO) NR_ANO,
	MONTH(DT_NASCIMENTO) NR_MES,
	((YEAR(DT_NASCIMENTO)*100)+MONTH(DT_NASCIMENTO)) NR_ANOMES
FROM 
	POC_DB.CLIENTE_PF
GROUP BY 
	(YEAR(DT_NASCIMENTO)*10000) + (MONTH(DT_NASCIMENTO)*100) + DAY(DT_NASCIMENTO),
	DT_NASCIMENTO,
	YEAR(DT_NASCIMENTO),
	MONTH(DT_NASCIMENTO),
	((YEAR(DT_NASCIMENTO)*100)+MONTH(DT_NASCIMENTO));
	
	
	
INSERT INTO DW_REG.DIM_PERIODO_BKP
SELECT
	(YEAR(DT_PAGAMENTO)*10000) + (MONTH(DT_PAGAMENTO)*100) + DAY(DT_PAGAMENTO) AS CD_PERIODO,
	DT_PAGAMENTO,
	YEAR(DT_PAGAMENTO) NR_ANO,
	MONTH(DT_PAGAMENTO) NR_MES,
	((YEAR(DT_PAGAMENTO)*100)+MONTH(DT_PAGAMENTO)) NR_ANOMES
FROM 
	POC_DB.FATURA_PF
GROUP BY 
	(YEAR(DT_PAGAMENTO)*10000) + (MONTH(DT_PAGAMENTO)*100) + DAY(DT_PAGAMENTO),
	DT_PAGAMENTO,
	YEAR(DT_PAGAMENTO),
	MONTH(DT_PAGAMENTO),
	((YEAR(DT_PAGAMENTO)*100)+MONTH(DT_PAGAMENTO));	
	
	
INSERT INTO DW_REG.DIM_PERIODO_BKP
SELECT
	(YEAR(DT_VENCIMENTO)*10000) + (MONTH(DT_VENCIMENTO)*100) + DAY(DT_VENCIMENTO) AS CD_PERIODO,
	DT_VENCIMENTO,
	YEAR(DT_VENCIMENTO) NR_ANO,
	MONTH(DT_VENCIMENTO) NR_MES,
	((YEAR(DT_VENCIMENTO)*100)+MONTH(DT_VENCIMENTO)) NR_ANOMES
FROM 
	POC_DB.FATURA_PF
GROUP BY 
	(YEAR(DT_VENCIMENTO)*10000) + (MONTH(DT_VENCIMENTO)*100) + DAY(DT_VENCIMENTO),
	DT_VENCIMENTO,
	YEAR(DT_VENCIMENTO),
	MONTH(DT_VENCIMENTO),
	((YEAR(DT_VENCIMENTO)*100)+MONTH(DT_VENCIMENTO));	


INSERT INTO DW_REG.DIM_PERIODO_BKP
SELECT
	(YEAR(DT_LEITURA)*10000) + (MONTH(DT_LEITURA)*100) + DAY(DT_LEITURA) AS CD_PERIODO,
	DT_LEITURA,
	YEAR(DT_LEITURA) NR_ANO,
	MONTH(DT_LEITURA) NR_MES,
	((YEAR(DT_LEITURA)*100)+MONTH(DT_LEITURA)) NR_ANOMES
FROM 
	POC_DB.FATURA_PF
GROUP BY 
	(YEAR(DT_LEITURA)*10000) + (MONTH(DT_LEITURA)*100) + DAY(DT_LEITURA),
	DT_LEITURA,
	YEAR(DT_LEITURA),
	MONTH(DT_LEITURA),
	((YEAR(DT_LEITURA)*100)+MONTH(DT_LEITURA));	
	
	
TRUNCATE TABLE DW_REG.DIM_PERIODO;

INSERT INTO DW_REG.DIM_PERIODO
SELECT
	CD_PERIODO,
	DT_PERIODO,
	NR_ANO,
	NR_MES,
	NR_ANOMES
FROM 
	DW_REG.DIM_PERIODO_BKP
GROUP BY 
	CD_PERIODO,
	DT_PERIODO,
	NR_ANO,
	NR_MES,
	NR_ANOMES;
	
	
DROP TABLE IF EXISTS DW_REG.DIM_PERIODO_BKP;	