
TRUNCATE TABLE DW_REG.DIM_CIDADE;

INSERT INTO DW_REG.DIM_CIDADE 
SELECT
	row_number()over() AS CD_CIDADE,
	CID.DS_CIDADE,
	CID.CD_UF
FROM
(
	SELECT
		DS_CIDADE,
		UF.CD_UF
	FROM
		POC_DB.CLIENTE_FATURA_PF PF
		INNER JOIN DW_REG.DIM_UF UF
			ON PF.DS_UF = UF.DS_UF
	GROUP BY 
		DS_CIDADE,
		UF.CD_UF
)CID;