
TRUNCATE TABLE DW_REG.DIM_RELIGIAO;

INSERT INTO DW_REG.DIM_RELIGIAO 
SELECT
	row_number()over() AS CD_RELIGIAO,
	REL.DS_RELIGIAO
FROM
(
	SELECT
		DS_RELIGIAO
	FROM
		POC_DB.CLIENTE_FATURA_PF
	GROUP BY 
		DS_RELIGIAO
)REL;