
TRUNCATE TABLE DW_REG.FAT_PAGAMENTO_FATURA;

INSERT INTO DW_REG.FAT_PAGAMENTO_FATURA
SELECT
	PF.CD_FATURA,
	PF.CD_CLIENTE,
	UND.CD_UND_CONSUMIDORA,
	CID.CD_CIDADE,
	CID.CD_UF,
	DTL.CD_PERIODO AS CD_DT_LEITURA,
	DTV.CD_PERIODO AS CD_DT_VENCIMENTO,
	DTP.CD_PERIODO AS CD_DT_PAGAMENTO,
	PF.VR_FATURA AS VR_FATURA,
	PF.QT_CONSUMO_KWh AS QT_CONSUMO_KWh
	
FROM
	POC_DB.CLIENTE_FATURA_PF PF
	LEFT JOIN DW_REG.DIM_UNIDADE_CONSUMIDORA UND
		ON PF.CD_UND_CONSUMIDORA = UND.DS_UND_CONSUMIDORA

	LEFT JOIN DW_REG.DIM_CIDADE CID
		ON PF.DS_CIDADE = CID.DS_CIDADE
		
	LEFT JOIN DW_REG.DIM_PERIODO DTL
		ON PF.DT_LEITURA = DTL.DT_PERIODO
		
    LEFT JOIN DW_REG.DIM_PERIODO DTV
		ON PF.DT_VENCIMENTO = DTV.DT_PERIODO			
		
    LEFT JOIN DW_REG.DIM_PERIODO DTP
		ON PF.DT_PAGAMENTO = DTP.DT_PERIODO			
		
GROUP BY
	PF.CD_FATURA,
	PF.CD_CLIENTE,
	UND.CD_UND_CONSUMIDORA,
	CID.CD_CIDADE,
	CID.CD_UF,
	DTL.CD_PERIODO,
	DTV.CD_PERIODO,
	DTP.CD_PERIODO,
	PF.VR_FATURA,
	PF.QT_CONSUMO_KWh
;