DROP TABLE IF EXISTS POC_DB.CLIENTE_PF_BKP_2;

CREATE TABLE POC_DB.CLIENTE_PF_BKP_2
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC
AS 
SELECT 
		
		CD_CLIENTE,
		NR_CPF,
		NM_NOME AS NM_CLIENTE,
		FLOOR(DATEDIFF(CURRENT_DATE, CLI.DT_NASCIMENTO)/365) NR_IDADE,
		DT_NASCIMENTO,
		DS_ETNIA,
		DS_RELIGIAO,
		DS_SEXO,
		DS_ESTADO_CIVIL,
		DS_NACIONALIDADE,
		DS_NATURALIDADE,
		DS_LOGRADOURO,
		DS_CIDADE,
		DS_UF,
		NR_CEP

	FROM POC_DB.CLIENTE_PF_BKP;