DROP TABLE IF EXISTS DW_REG.DIM_UNIDADE_CONSUMIDORA;
DROP TABLE IF EXISTS DW_REG.DIM_UF;
DROP TABLE IF EXISTS DW_REG.DIM_CIDADE;
DROP TABLE IF EXISTS DW_REG.DIM_PERIODO;
DROP TABLE IF EXISTS DW_REG.DIM_ETNIA;
DROP TABLE IF EXISTS DW_REG.DIM_RELIGIAO;
DROP TABLE IF EXISTS DW_REG.DIM_NACIONALIDADE;
DROP TABLE IF EXISTS DW_REG.DIM_NATURALIDADE;
DROP TABLE IF EXISTS DW_REG.DIM_CLIENTE;
DROP TABLE IF EXISTS DW_REG.FAT_PAGAMENTO_FATURA;

DROP DATABASE DW_REG;

CREATE DATABASE DW_REG;

USE DW_REG;



CREATE TABLE DW_REG.DIM_CLIENTE 
(
	CD_CLIENTE BIGINT NOT NULL, 
	NR_CPF VARCHAR (12), 
	NM_CLIENTE VARCHAR (100), 
	DS_SEXO CHAR(1), 
	DS_ESTADO_CIVIL VARCHAR (10),
	NR_IDADE INT,
	CD_DT_NASCIMENTO INT ,
	DS_LOGRADOURO VARCHAR (100),
	NM_CEP VARCHAR (9),
	CD_ETNIA INT ,
	CD_RELIGIAO INT ,
	CD_NACIONALIDADE INT ,
	CD_NATURALIDADE INT 
)	
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



CREATE TABLE DW_REG.DIM_PERIODO
(
	CD_PERIODO INT NOT NULL,
	DT_PERIODO DATE NOT NULL,
	NR_ANO INT,
	NR_MES INT,
	NR_ANOMES INT
	
)	
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;	



CREATE TABLE DW_REG.DIM_ETNIA
(
	CD_ETNIA INT NOT NULL,
	DS_ETNIA VARCHAR (9) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;	



CREATE TABLE DW_REG.DIM_RELIGIAO
(
	CD_RELIGIAO INT NOT NULL,
	DS_RELIGIAO VARCHAR (20) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;	



CREATE TABLE DW_REG.DIM_NACIONALIDADE
(	
	CD_NACIONALIDADE INT NOT NULL,
	DS_NACIONALIDADE VARCHAR (100) NOT NULL
)	
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;	



CREATE TABLE DW_REG.DIM_NATURALIDADE
(	
	CD_NATURALIDADE INT NOT NULL,
	DS_NATURALIDADE VARCHAR (100) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



CREATE TABLE DW_REG.DIM_CIDADE
(	
	CD_CIDADE INT NOT NULL,
	DS_CIDADE VARCHAR (100) NOT NULL,
	CD_UF INT 
)	
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



CREATE TABLE DW_REG.DIM_UF
(		
	CD_UF INT NOT NULL,
	DS_UF CHAR (100) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



CREATE TABLE DW_REG.DIM_UNIDADE_CONSUMIDORA
(		
	CD_UND_CONSUMIDORA INT NOT NULL,
	DS_UND_CONSUMIDORA VARCHAR(14) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



CREATE TABLE DW_REG.FAT_PAGAMENTO_FATURA
(
	CD_FATURA BIGINT NOT NULL,
	CD_CLIENTE BIGINT ,
	CD_UND_CONSUMIDORA INT ,
	CD_CIDADE INT ,
	CD_UF INT ,
	CD_DT_LEITURA INT ,
	CD_DT_VENCIMENTO INT ,
	CD_DT_PAGAMENTO INT ,
	VR_FATURA DECIMAL (15,2) NOT NULL,
	QT_CONSUMO_KWh DECIMAL (15,2) NOT NULL
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC;



ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (CD_CLIENTE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_PERIODO ADD CONSTRAINT PK_DIM_PERIODO PRIMARY KEY (CD_PERIODO) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_ETNIA ADD CONSTRAINT PK_DIM_ETNIA PRIMARY KEY (CD_ETNIA) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_RELIGIAO ADD CONSTRAINT PK_DIM_RELIGIAO PRIMARY KEY (CD_RELIGIAO) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_NACIONALIDADE ADD CONSTRAINT PK_DIM_NACIONALIDADE PRIMARY KEY (CD_NACIONALIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_NATURALIDADE ADD CONSTRAINT PK_DIM_NATURALIDADE PRIMARY KEY (CD_NATURALIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_CIDADE ADD CONSTRAINT PK_DIM_CIDADE PRIMARY KEY (CD_CIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_UF ADD CONSTRAINT PK_DIM_UF PRIMARY KEY (CD_UF) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_UNIDADE_CONSUMIDORA ADD CONSTRAINT PK_DIM_UNIDADE_CONSUMIDORA PRIMARY KEY (CD_UND_CONSUMIDORA) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT PK_FAT_PAGAMENTO_FATURA PRIMARY KEY (CD_FATURA) DISABLE NOVALIDATE;

ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT FK_DIM_CLIENTE_DIM_ETNIA FOREIGN KEY (CD_ETNIA) REFERENCES DW_REG.DIM_ETNIA (CD_ETNIA) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT FK_DIM_CLIENTE_DIM_RELIGIAO FOREIGN KEY (CD_RELIGIAO) REFERENCES DW_REG.DIM_RELIGIAO (CD_RELIGIAO) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT FK_DIM_CLIENTE_DIM_NACIONALIDADE FOREIGN KEY (CD_NACIONALIDADE) REFERENCES DW_REG.DIM_NACIONALIDADE (CD_NACIONALIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT FK_DIM_CLIENTE_DIM_NATURALIDADE FOREIGN KEY (CD_NATURALIDADE) REFERENCES DW_REG.DIM_NATURALIDADE (CD_NATURALIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.DIM_CLIENTE ADD CONSTRAINT FK_DIM_CLIENTE_DIM_PERIODO_DT_NASCIMENTO FOREIGN KEY (CD_DT_NASCIMENTO) REFERENCES DW_REG.DIM_PERIODO (CD_PERIODO) DISABLE NOVALIDATE;


ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_CLIENTE FOREIGN KEY (CD_CLIENTE) REFERENCES DW_REG.DIM_CLIENTE (CD_CLIENTE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_UNIDADE_CONSUMIDORA FOREIGN KEY (CD_UND_CONSUMIDORA) REFERENCES DW_REG.DIM_UNIDADE_CONSUMIDORA (CD_UND_CONSUMIDORA) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_CIDADE FOREIGN KEY (CD_CIDADE) REFERENCES DW_REG.DIM_CIDADE (CD_CIDADE) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_UF FOREIGN KEY (CD_UF) REFERENCES DW_REG.DIM_UF (CD_UF) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_PERIODO_LEITURA FOREIGN KEY (CD_DT_LEITURA) REFERENCES DW_REG.DIM_PERIODO (CD_PERIODO) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_PERIODO_VENCIMENTO FOREIGN KEY (CD_DT_VENCIMENTO) REFERENCES DW_REG.DIM_PERIODO (CD_PERIODO) DISABLE NOVALIDATE;
ALTER TABLE DW_REG.FAT_PAGAMENTO_FATURA ADD CONSTRAINT FK_FAT_PAGAMENTO_DIM_PERIODO_PAGAMENTO FOREIGN KEY (CD_DT_PAGAMENTO) REFERENCES DW_REG.DIM_PERIODO (CD_PERIODO) DISABLE NOVALIDATE;

