USE POC_DB;

DROP TABLE IF EXISTS POC_DB.FATURA_PF_CSV;
CREATE EXTERNAL TABLE POC_DB.FATURA_PF_CSV
(
        CD_FATURA BIGINT,
        CD_CLIENTE BIGINT,
        CD_UND_CONSUMIDORA VARCHAR (14),
        DT_VENCIMENTO VARCHAR(10),
        DT_PAGAMENTO VARCHAR(10),
        DT_LEITURA VARCHAR(10),
        VR_FATURA DECIMAL (9,2),
        QT_CONSUMO_KWh DECIMAL (9,2),
        MES_VENCIMENTO INT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
TBLPROPERTIES ("skip.header.line.count"="1");