
DROP TABLE IF EXISTS POC_DB.CLIENTE_FATURA_PF;

CREATE TABLE POC_DB.CLIENTE_FATURA_PF
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS ORC
AS SELECT
	
	CLI.CD_CLIENTE, 
	CLI.NR_CPF, 
	CLI.NM_CLIENTE, 
	FLOOR(DATEDIFF(CURRENT_DATE, CLI.DT_NASCIMENTO)/365) NR_IDADE,
	CLI.DT_NASCIMENTO,
	CLI.DS_ETNIA,
	CLI.DS_RELIGIAO, 
	CLI.DS_SEXO, 
	CLI.DS_ESTADO_CIVIL,
	CLI.DS_NACIONALIDADE,
	CLI.DS_NATURALIDADE,
	CLI.DS_LOGRADOURO,
	CLI.DS_CIDADE,
	CLI.DS_UF,
	CLI.NR_CEP,
	FAT.CD_FATURA,
	FAT.CD_UND_CONSUMIDORA,
	FAT.DT_VENCIMENTO,
	FAT.DT_PAGAMENTO,
	FAT.DT_LEITURA,
	FAT.VR_FATURA,
	FAT.QT_CONSUMO_KWh
	
FROM
	POC_DB.CLIENTE_PF CLI
	INNER JOIN POC_DB.FATURA_PF FAT
		ON CLI.CD_CLIENTE = FAT.CD_CLIENTE;