
TRUNCATE TABLE POC_DB.FATURA_PF;

INSERT INTO POC_DB.FATURA_PF
SELECT 
	
	CD_FATURA,
	CD_CLIENTE,
	CD_UND_CONSUMIDORA,
	TO_DATE(SUBSTR(DT_VENCIMENTO,7,4) || '-' || SUBSTR(DT_VENCIMENTO, 4,2) || '-' || SUBSTR(DT_VENCIMENTO, 1, 2)) DT_VENCIMENTO,
	TO_DATE(SUBSTR(DT_PAGAMENTO,7,4) || '-' || SUBSTR(DT_PAGAMENTO, 4,2) || '-' || SUBSTR(DT_PAGAMENTO, 1, 2)) DT_PAGAMENTO,
	TO_DATE(SUBSTR(DT_LEITURA,7,4) || '-' || SUBSTR(DT_LEITURA, 4,2) || '-' || SUBSTR(DT_LEITURA, 1, 2)) DT_LEITURA,
	VR_FATURA,
	QT_CONSUMO_KWh,
        MES_VENCIMENTO
	

FROM POC_DB.FATURA_PF_CSV;